basedir="$(cd $(dirname $0); pwd)"
source "$basedir/paths.zsh"
cp "$(terminalSettingsBackupPath)" "$(terminalSettingsPath)"
cp "$(vscodeSettingsBackupPath)" "$(vscodeSettingsPath)"
cp "$(vscodeKeybindingsBackupPath)" "$(vscodeKeybindingsPath)"
cp "$(vscodeTasksBackupPath)" "$(vscodeTasksPath)"
