filetype off
syntax on

source $HOME/.vim/env.vim
source $HOME/.vim/core.vim
if g:is_wsl
  source $HOME/.vim/wsl.vim
endif
source $HOME/.vim/dein.vim
source $HOME/.vim/fmt.vim
source $HOME/.vim/shortcuts.vim

filetype indent plugin on
