source "$HOME/.zsh/prompt.zsh"
source "$HOME/.zsh/completion.zsh"

eval "$(rbenv init -)"

export EDITOR=vim

orphans() {
  if [[ ! -n $(pacman -Qdt) ]]; then
    echo "No orphans to remove."
  else
    sudo pacman -Rns $(pacman -Qdtq)
  fi
}


precmd () { 
  vcs_info 
  prompt
}


# cd

chpwd() {
  check_pyvenv
}

check_pyvenv() {
  if [[ -n "$VIRTUAL_ENV" ]]; then
    case $(pwd) in
      $VIRTUAL_ENV* ) ;; # In venv
      *             ) deactivate ;;
    esac
  elif [[ -r 'bin/activate' ]]; then # Can read bin/activate and venv hasn't activated
    source 'bin/activate'
  fi
}

# enter

do_enter() {
  if [ -n "$BUFFER" ]; then
    zle accept-line
    return 0
  fi  
  echo
  ls
  zle reset-prompt
}
zle -N do_enter
bindkey '^m' do_enter
