#!/bin/sh

basedir=$(cd $(dirname $0); pwd)

targets="$@"
if [ $# -eq 0 ]
then
  # Run all tests if no arguments are given
  targets="$basedir"
fi

bats -r -x --print-output-on-failure --show-output-of-passing-tests --report-formatter tap --output $basedir "$targets"
