#!/bin/sh

COMMIT_MSG_FILE="$1"

# Don't change commit message already exists (for git commit --ammend)
ORIGINAL_FIRST_LINE=$(head -n1 "$COMMIT_MSG_FILE")
if [ -n "$ORIGINAL_FIRST_LINE" ]
then
  exit 0
fi

STATUS=$(git status -s | grep '^[MAD]')
if [ "$(echo "$STATUS" | wc -l)" -eq "1" ]
then
  MSG="$(echo "$STATUS" | sed 's/^M /Update/' | sed 's/^A /Add/' | sed 's/^D /Delete/g')"
fi
ORIGINAL_CONTENT=$(cat $COMMIT_MSG_FILE)
echo "$MSG$ORIGINAL_CONTENT" > "$COMMIT_MSG_FILE"
